apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: pythonapp
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "46591"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: pythonapp
    spec:
      containers:
      - env:
        - name: APP_ID
          value: pythonapp
        - name: APP_CHANNEL_ADDRESS
        - name: DAPR_METRICS_PORT
          value: "46591"
        image: ghcr.io/dapr/samples/hello-k8s-python:latest
        imagePullPolicy: Always
        name: pythonapp
        resources: {}
